// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paginate/paginate.proto

/*
Package paginate is a generated protocol buffer package.

It is generated from these files:
	paginate/paginate.proto

It has these top-level messages:
	PageOptions
	PageResult
*/
package paginate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Action : PreviousPage, NextPage
// Action default NextPage
type PageOptions struct {
	PageSize int32  `protobuf:"varint,2,opt,name=PageSize" json:"PageSize,omitempty"`
	MaxId    int32  `protobuf:"varint,3,opt,name=MaxId" json:"MaxId,omitempty"`
	Action   string `protobuf:"bytes,4,opt,name=Action" json:"Action,omitempty"`
}

func (m *PageOptions) Reset()                    { *m = PageOptions{} }
func (m *PageOptions) String() string            { return proto.CompactTextString(m) }
func (*PageOptions) ProtoMessage()               {}
func (*PageOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PageOptions) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageOptions) GetMaxId() int32 {
	if m != nil {
		return m.MaxId
	}
	return 0
}

func (m *PageOptions) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

// total TotalRecouds entries， total TotalPages pages
type PageResult struct {
	TotalRecords int32 `protobuf:"varint,1,opt,name=TotalRecords" json:"TotalRecords,omitempty"`
	TotalPages   int32 `protobuf:"varint,2,opt,name=TotalPages" json:"TotalPages,omitempty"`
	PageSize     int32 `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
	MaxId        int32 `protobuf:"varint,4,opt,name=MaxId" json:"MaxId,omitempty"`
	MinId        int32 `protobuf:"varint,5,opt,name=MinId" json:"MinId,omitempty"`
}

func (m *PageResult) Reset()                    { *m = PageResult{} }
func (m *PageResult) String() string            { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()               {}
func (*PageResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PageResult) GetTotalRecords() int32 {
	if m != nil {
		return m.TotalRecords
	}
	return 0
}

func (m *PageResult) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *PageResult) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageResult) GetMaxId() int32 {
	if m != nil {
		return m.MaxId
	}
	return 0
}

func (m *PageResult) GetMinId() int32 {
	if m != nil {
		return m.MinId
	}
	return 0
}

func init() {
	proto.RegisterType((*PageOptions)(nil), "paginate.PageOptions")
	proto.RegisterType((*PageResult)(nil), "paginate.PageResult")
}

func init() { proto.RegisterFile("paginate/paginate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x48, 0x4c, 0xcf,
	0xcc, 0x4b, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0xa5, 0x70, 0x2e, 0xee, 0x80, 0xc4, 0xf4, 0x54, 0xff, 0x82, 0x92, 0xcc, 0xfc, 0xbc, 0x62,
	0x21, 0x29, 0x2e, 0x0e, 0x10, 0x37, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35,
	0x08, 0xce, 0x17, 0x12, 0xe1, 0x62, 0xf5, 0x4d, 0xac, 0xf0, 0x4c, 0x91, 0x60, 0x06, 0x4b, 0x40,
	0x38, 0x42, 0x62, 0x5c, 0x6c, 0x8e, 0xc9, 0x20, 0xcd, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x50, 0x9e, 0xd2, 0x0c, 0x46, 0x2e, 0x2e, 0x90, 0xd6, 0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x21,
	0x25, 0x2e, 0x9e, 0x90, 0xfc, 0x92, 0xc4, 0x9c, 0xa0, 0xd4, 0xe4, 0xfc, 0xa2, 0x94, 0x62, 0x09,
	0x46, 0xb0, 0x19, 0x28, 0x62, 0x42, 0x72, 0x5c, 0x5c, 0x60, 0x3e, 0x48, 0x5b, 0x31, 0xd4, 0x7a,
	0x24, 0x11, 0x14, 0xc7, 0x31, 0xe3, 0x72, 0x1c, 0x0b, 0xb2, 0xe3, 0x40, 0xa2, 0x99, 0x79, 0x9e,
	0x29, 0x12, 0xac, 0x50, 0x51, 0x10, 0x27, 0x89, 0x0d, 0x1c, 0x08, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x39, 0x2e, 0xb3, 0x73, 0x1f, 0x01, 0x00, 0x00,
}
