// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paginate/paginate.proto

/*
Package paginate is a generated protocol buffer package.

It is generated from these files:
	paginate/paginate.proto

It has these top-level messages:
	Paginate
*/
package paginate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Paginate struct {
	TotalRecouds int32 `protobuf:"varint,1,opt,name=TotalRecouds" json:"TotalRecouds,omitempty"`
	TotalPages   int32 `protobuf:"varint,2,opt,name=TotalPages" json:"TotalPages,omitempty"`
	PageSize     int32 `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
	PageNumber   int32 `protobuf:"varint,4,opt,name=PageNumber" json:"PageNumber,omitempty"`
}

func (m *Paginate) Reset()                    { *m = Paginate{} }
func (m *Paginate) String() string            { return proto.CompactTextString(m) }
func (*Paginate) ProtoMessage()               {}
func (*Paginate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Paginate) GetTotalRecouds() int32 {
	if m != nil {
		return m.TotalRecouds
	}
	return 0
}

func (m *Paginate) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Paginate) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Paginate) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*Paginate)(nil), "paginate.Paginate")
}

func init() { proto.RegisterFile("paginate/paginate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x48, 0x4c, 0xcf,
	0xcc, 0x4b, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0xa5, 0x2e, 0x46, 0x2e, 0x8e, 0x00, 0x28, 0x47, 0x48, 0x89, 0x8b, 0x27, 0x24, 0xbf, 0x24,
	0x31, 0x27, 0x28, 0x35, 0x39, 0xbf, 0x34, 0xa5, 0x58, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08,
	0x45, 0x4c, 0x48, 0x8e, 0x8b, 0x0b, 0xcc, 0x0f, 0x48, 0x4c, 0x4f, 0x2d, 0x96, 0x60, 0x02, 0xab,
	0x40, 0x12, 0x11, 0x92, 0x02, 0x9b, 0x97, 0x1a, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0x0c, 0x96, 0x85,
	0xf3, 0x41, 0x7a, 0x41, 0x6c, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x16, 0x88, 0x5e, 0x84,
	0x48, 0x12, 0x1b, 0xd8, 0x75, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x19, 0xe9, 0xdf,
	0xb8, 0x00, 0x00, 0x00,
}
